version: "3.9"
services:
  tienda:
    build:
      context: .
      dockerfile: Dockerfile
    image: tienda-disiento:latest
    restart: unless-stopped
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - tienda_data:/app/data

volumes:
  tienda_data:
